repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^integration-tests/jbang/EmptyPIPComments\.j$
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-xml
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: mixed-line-ending
        args: ['--fix=no']
-   repo: local
    hooks:
    -   id: maven-validate-spotless
        name: Maven validate & spotless:apply
        entry: ./mvnw
        args: ['validate', '-DskipJavainterfacegen=true', 'spotless:apply']
        language: system
        pass_filenames: false
