/*
 * Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * The Universal Permissive License (UPL), Version 1.0
 *
 * Subject to the condition set forth below, permission is hereby granted to any
 * person obtaining a copy of this software, associated documentation and/or
 * data (collectively the "Software"), free of charge and under any and all
 * copyright rights in the Software, and any and all patent rights owned or
 * freely licensable by each licensor hereunder covering either (i) the
 * unmodified Software as contributed to or provided by such licensor, or (ii)
 * the Larger Works (as defined below), to deal in both
 *
 * (a) the Software, and
 *
 * (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
 * one is included with the Software each a "Larger Work" to which the Software
 * is contributed by such licensors),
 *
 * without restriction, including without limitation the rights to copy, create
 * derivative works of, display, perform, and distribute the Software and make,
 * use, sell, offer for sale, import, export, have made, and have sold the
 * Software and the Larger Work(s), and to sublicense the foregoing rights on
 * either these or other terms.
 *
 * This license is subject to the following condition:
 *
 * The above copyright notice and either this complete permission notice or at a
 * minimum a reference to the UPL must be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.graalvm.python.maven.plugin;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.ProjectBuilder;
import org.graalvm.python.embedding.tools.vfs.VFSUtils;

import javax.inject.Inject;
import java.io.IOException;
import java.nio.file.Path;

@Mojo(name = "lock-packages", requiresDependencyCollection = ResolutionScope.COMPILE_PLUS_RUNTIME, requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME)
public class LockPackagesMojo extends AbstractGraalPyMojo {

	protected static final String LOCK_FILE_HEADER = """
			This file was generated by maven goal 'org.graalvm.python:graalpy-maven-plugin:lock-packages'.

			WARNING: Any manual changes are done at your own risk and will be overwritten when the goal is executed.

			This file is meant to be tracked in a version control system.

			This file contains a list of all required Python packages with their specific versions,
			based on the packages defined in the plugin configuration and their dependencies.
			""";
    public static final String MISSING_DEPENDENCY_CONFIGURATION_ERROR = """
            In order to run the lock-packages goal you must declare Python dependencies in the graalpy-maven-plugin configuration.
            
            You must configure Python dependencies in one of the following ways:
            
              Option 1: Use <packages> with inline versioned package entries:
            
                <plugin>
                  <groupId>org.graalvm.python</groupId>
                  <artifactId>graalpy-maven-plugin</artifactId>
                  <configuration>
                    <packages>
                      <package>{package_name}=={package_version}</package>
                    </packages>
                    ...
                  </configuration>
                </plugin>
            
              Option 2: Use a pip-compatible requirements.txt file:
            
                <plugin>
                  <groupId>org.graalvm.python</groupId>
                  <artifactId>graalpy-maven-plugin</artifactId>
                  <configuration>
                    <requirementsFile>requirements.txt</requirementsFile>
                    ...
                  </configuration>
                </plugin>
            
            IMPORTANT:
              • The requirementsFile workflow follows pip's native behavior.
              • GraalPy lock files are NOT used or generated when requirementsFile is specified.
              • The 'lock-packages' goal is NOT supported with <requirementsFile>.
              • Users are expected to manage locking / freezing themselves using pip conventions (e.g., pip freeze).
              • Do not define both <packages> and <requirementsFile> at the same time.
              • The <configuration> section must be declared on the graalpy-maven-plugin itself,
                not inside a specific execution.
            
            For more details, see:
            https://github.com/oracle/graalpython/blob/master/docs/user/Embedding-Build-Tools.md
            """;


    @Inject
	public LockPackagesMojo(ProjectBuilder projectBuilder) {
		super(projectBuilder);
	}

	public void execute() throws MojoExecutionException {
		preExec(false);
		checkEmptyPackages();

		manageVenv();
		listGraalPyResources();

		postExec();
	}

	protected void manageVenv() throws MojoExecutionException {
		Path venvDirectory = getVenvDirectory();
		MavenDelegateLog log = new MavenDelegateLog(getLog());
		Path requirements = getLockFile();

		try {
			VFSUtils.lockPackages(venvDirectory, packages, requirements, LOCK_FILE_HEADER, createLauncher(),
					getGraalPyVersion(project), log);
		} catch (IOException e) {
			throw new MojoExecutionException(String.format("failed to create venv %s", venvDirectory), e);
		}
	}

    private void checkEmptyPackages() throws MojoExecutionException {
        Path reqFilePath = resolveReqFile();
        boolean emptyPackages = packages == null || packages.isEmpty();
        boolean requirementsExists = reqFilePath != null;
        if (emptyPackages && !requirementsExists) {
            getLog().error("");
            getLog().error(MISSING_DEPENDENCY_CONFIGURATION_ERROR);
            getLog().error("");
            throw new MojoExecutionException("Missing Python dependency configuration.");
        }
    }
}
