from typing import Any

class UseSite:
    """Methods demonstrating wildcard and raw type handling at use sites."""
    def __init__(self) -> None: ...
    def anyList(self) -> list[Any]: ...
    def listRaw(self, raw: list[Any]) -> list[str]: ...
    def mapWild(self) -> dict[Any, str]: ...

